### ISSUE TITLE
It rerturns 1 . what is the error, curl --location --request POST 'http://164.90.198.193:7777' --header 'Content-Type: application/json' --data-raw '{ "jsonrpc": "2.0", "method": "chain_get_state_root_hash", "params": null, "id": 1 }'

### ISSUE THREAD

**Issue by malingzhao** [casper-ecosystem/casper-js-sdk#105]

**Comment by hoffmannjan** [comment]
I think you are missing `/rpc` in your URL.
other than that it looks like your problem is not related to `casper-js-sdk` and more likely to [`casper-node`](https://github.com/casper-network/casper-node), so closing it. If you have any more questions please create a new issue [here](https://github.com/casper-network/casper-node)
